; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
;--------------- select you board --------------;


;--------------- select a example --------------;
; src_dir = examples/bq25896/main               ;
; src_dir = examples/bq27220/main               ;
; src_dir = examples/display_test/main          ; 
; src_dir = examples/GPS/main                   ;
; src_dir = examples/lora_recv/main             ;
; src_dir = examples/lora_send/main             ;
; src_dir = examples/lvgl_test/main             ;
; src_dir = examples/rtc_pcf8563/main           ;
; src_dir = examples/sd_card/main               ;
; src_dir = examples/touch/main                 ;
; src_dir = examples/io_extend/main             ;
; src_dir = examples/nvs_test                   ;
src_dir = examples/factory/main               ;

;******************************************************
; Example routines using the FastEPD library
;******************************************************
; src_dir = examples/FastEPD/getting_started    ;
; src_dir = examples/FastEPD/gif_player         ;
; src_dir = examples/FastEPD/grayscale_test     ;
; src_dir = examples/FastEPD/show_jpeg          ;
; src_dir = examples/FastEPD_lvgl_test/main     ;

;----------------------------------------------;
boards_dir = boards
[env:T5_E_PAPER_S3_V7]
platform = espressif32@6.5.0
board = T5-ePaper-S3
framework = arduino
upload_speed =  921600
monitor_speed = 115200
; monitor_port = COM136
monitor_filters = esp32_exception_decoder
; board_build.partition = default_16MB.csv
; extra_scripts =  ./script/pos_extra_script.py

build_flags = 
    -DBOARD_HAS_PSRAM
    -DPSRAM_SPEED=120MHz

    ; Enable -DARDUINO_USB_CDC_ON_BOOT will start printing and wait for terminal access during startup
    -DARDUINO_USB_CDC_ON_BOOT=1

    -DCORE_DEBUG_LEVEL=5

    ; -DLOG_PORT=Serial

    -DDISABLE_ALL_LIBRARY_WARNINGS

    -Wl,--gc-sections

lib_deps =
    ; lvgl/lvgl@8.4.0
    ; lewisxhe/SensorLib@0.2.2
    ; lewisxhe/XPowersLib@^0.2.7
    Wire
    SPI
    bitbank2/PNGdec
